# Generated by Django 6.0.3 on 2026-03-22 16:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('veg', 'Vegetarian'), ('nonveg', 'Non-Vegetarian'), ('skip', 'Skip (Not Eating)')], max_length=10)),
                ('meal_session', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], default='lunch', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meal Price',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Monday of the week this schedule applies from')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Weekly Schedule',
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='DailyBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_session', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=10)),
                ('meal_type', models.CharField(choices=[('veg', 'Vegetarian'), ('nonveg', 'Non-Vegetarian'), ('skip', 'Skip (Not Eating)')], max_length=10)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('attended', 'Attended'), ('missed', 'Missed (Still Billed)'), ('cancelled', 'Cancelled')], default='booked', max_length=10)),
                ('source', models.CharField(choices=[('auto', 'Auto (Weekly Schedule)'), ('override', 'Manual Override')], default='auto', max_length=10)),
                ('price_snapshot', models.DecimalField(decimal_places=2, default=0, help_text='Price at time of booking (immutable for billing)', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_bookings', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Daily Booking',
                'ordering': ['-date', 'meal_session'],
                'unique_together': {('student', 'date', 'meal_session')},
            },
        ),
        migrations.CreateModel(
            name='MenuConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(help_text='Date from which this menu applies')),
                ('meal_session', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], default='lunch', max_length=10)),
                ('has_veg', models.BooleanField(default=True)),
                ('has_nonveg', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, help_text="Today's menu description")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Menu Configuration',
                'ordering': ['-effective_date', 'meal_session'],
                'unique_together': {('effective_date', 'meal_session')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('meal_session', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], default='lunch', max_length=10)),
                ('meal_preference', models.CharField(choices=[('veg', 'Vegetarian'), ('nonveg', 'Non-Vegetarian'), ('skip', 'Skip (Not Eating)')], default='veg', max_length=10)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='meals.weeklyschedule')),
            ],
            options={
                'ordering': ['day_of_week', 'meal_session'],
                'unique_together': {('schedule', 'day_of_week', 'meal_session')},
            },
        ),
    ]
