# Generated by Django 6.0.3 on 2026-03-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuconfig',
            name='nonveg_items',
            field=models.TextField(blank=True, help_text='Non-Veg food items e.g: Chicken Curry, Rice, Roti'),
        ),
        migrations.AddField(
            model_name='menuconfig',
            name='veg_items',
            field=models.TextField(blank=True, help_text='Veg food items e.g: Dal, Rice, Roti, Sabzi'),
        ),
        migrations.AlterField(
            model_name='menuconfig',
            name='description',
            field=models.TextField(blank=True, help_text='General description (optional)'),
        ),
    ]
