# Generated by Django 6.0.3 on 2026-04-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_menuconfig_nonveg_items_menuconfig_veg_items_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menuconfig',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='menuconfig',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday'), (7, 'All Days (Default)')], default=7, help_text="Set a specific day or 'All Days' as default"),
        ),
        migrations.AlterUniqueTogether(
            name='menuconfig',
            unique_together={('effective_date', 'meal_session', 'day_of_week')},
        ),
        migrations.CreateModel(
            name='DayWiseMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('meal_session', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=10)),
                ('has_veg', models.BooleanField(default=True)),
                ('has_nonveg', models.BooleanField(default=False)),
                ('veg_items', models.TextField(blank=True, help_text='Veg food items for this day')),
                ('nonveg_items', models.TextField(blank=True, help_text='Non-Veg food items for this day')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Day-Wise Menu',
                'verbose_name_plural': 'Day-Wise Menus',
                'ordering': ['day_of_week', 'meal_session'],
                'unique_together': {('day_of_week', 'meal_session')},
            },
        ),
    ]
