# Generated by Django 6.0.3 on 2026-06-07 15:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_systemconfig_booking_deadline_hour_and_more'),
        ('meals', '0003_alter_menuconfig_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('date', models.DateField()),
                ('session', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=15)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_tokens', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Meal Token',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'date', 'session')},
            },
        ),
    ]
