# Generated by Django 6.0.3 on 2026-05-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='booking_deadline_hour',
            field=models.PositiveSmallIntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='warning_fraction',
            field=models.FloatField(default=0.6666666666666666),
        ),
    ]
