# Generated by Django 6.0.3 on 2026-07-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_systemconfig_booking_deadline_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='qr_base64',
            field=models.TextField(blank=True),
        ),
    ]
