# Generated by Django 6.0.3 on 2026-03-22 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('menu_change', 'Menu Changed'), ('price_change', 'Price Changed'), ('booking_cancelled', 'Booking Cancelled'), ('warning_pending', 'Pending Amount Warning'), ('card_blocked', 'Card Blocked'), ('card_unblocked', 'Card Unblocked'), ('general', 'General'), ('registration', 'Registration Update')], default='general', max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
