# Generated by Django 6.0.3 on 2026-03-22 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_token', models.UUIDField(help_text='Token scanned from QR code')),
                ('scan_result', models.CharField(choices=[('valid', 'Valid – Attendance Marked'), ('invalid_qr', 'Invalid QR Token'), ('not_booked', 'No Booking Found'), ('card_blocked', 'Card Blocked'), ('already_used', 'Already Attended'), ('not_approved', 'Student Not Approved')], max_length=20)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_log', to='meals.dailybooking')),
                ('scanned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Log',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
